name: dart
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  ffigen: ^4.1.2

flutter:
  uses-material-design: true
ffigen:
  llvm-path:
    - 'C:\lang\LLVM'
  name: rust_panic
  description:
  output: './test/dart/error_lib/rust_panic.dart'
  headers:
    entry-points:
      - './test/dart/error_lib/rust_panic/src/rust_panic.hpp'